### PR TITLE
issue-8: fixed never reached branch and update error response exceptions

### LINKED ISSUE #8: Modify never reached branches in do_request and print_error to properly print error messages and throw exceptions
Fixing: Client library only prints error messages but not raise errors when receives HTTP error codes (like 400, 404, 503...). Also it doesn't deal with some http responses because of the logic of some branches. 

https://jira.oceannetworks.ca/browse/DMAS-79608

### PR DESCRIPTION
**Pull request by IslaLi**
Modified print_error.m to print error messages (including error codes) for http 400 and 401, print standard error messages for other http responses. 

Modified prepare_exception.m to throw exception for each specific case

Modified do_request.m to print error messages and then throw exceptions if needed

### CODE REVIEW

File: onc/+util/do_request.m [hunk 1]
```diff
@@ -25,7 +25,9 @@
     % run and time request
     if showInfo, fprintf('\nRequesting URL:\n   %s\n', fullUrl); end
     tic
-    response = send(request, uri, options);
+    %response = send(request, uri, options);
```
Comment (KristenMeyerONC) [inline onc/+util/do_request.m]: You can remove this commented code

File: onc/+util/do_request.m [hunk 2]
```diff
@@ -47,22 +49,13 @@
...
-            % Down for maintenance
-            fprintf('\nERROR 503: Service unavailable.\nWe could be down for maintenance; ');
-            fprintf('visit https://data.oceannetworks.ca for more information.\n')
-            result = struct('errors', [struct('errorCode', 503, 'message', 'Service Unavailable')]);
         otherwise
-            result = response.Body.Data;
-            fprintf('\nERROR: The request failed with HTTP error %d\n', status)
+            util.print_error(response, fullUrl);
+            if status == 400 || status == 401
+                throw(util.prepare_exception(status,double(response.Body.Data.errors.errorCode)));
```
Comment (KristenMeyerONC) [inline onc/+util/do_request.m]: For readability can you put a space after the comma:
throw(util.prepare_exception(status, double(response.Body.Data.errors.errorCode)));

File: onc/+util/print_error.m [hunk 3]
```diff
@@ -4,32 +4,48 @@ function print_error(response, url)
...
-            fprintf('\nERROR %d: The request failed.\n', status)
-        end
+% helper function
+function print_error_message(payload)
+    % Make sure the payload was parsed automatically
+    if ~isstruct(payload)
+        payload = jsondecode(payload);
     end
+
+    %if isfield(payload, 'errors')
```
Comment (KristenMeyerONC) [inline onc/+util/print_error.m]: You can remove this commented code

**Review by KristenMeyerONC — CHANGES_REQUESTED** [review]
